spring:
    kafka:
        consumer:
            auto-offset-reset: earliest
            bootstrap-servers: 127.0.0.1:9092
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

            group-id: group_id
            properties:
                spring:
                    json:
                        use:
                            type:
                                headers: false

                        value:
                            default:
                                type: com.xavierbouclet.kafkademo.avro.Message
                schema.registry.url: http://localhost:8081/
                specific.avro.reader: true
    properties:
        spring:
            json:
                trusted:
                    packages: '*'

server:
    port: 8081

topic:
    name:
        consumer: quickstart
